dist: bionic
sudo: required
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.60.0/hugo_extended_0.60.0_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.60.0_Linux-64bit.deb
script:
  - mkdir deploy
  - cd doc
  - hugo
  - cd ..
  - cp -fr doc/public deploy
  - mv deploy/public deploy/doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: deploy
  repo: canokeys/canokeys.github.io
  on:
    branch: master
